### ISSUE TITLE
Why is a data cleansing component is applied to train data but not in test and validation data

### ISSUE THREAD

**Issue by clopezhrimac** [GoogleCloudPlatform/vertex-pipelines-end-to-end-samples#45]
In training xgboost pipeline :

![image](https://github.com/GoogleCloudPlatform/vertex-pipelines-end-to-end-samples/assets/84086143/0fbc15a8-33b3-4aaf-906f-5a5b3ccb0b3c)

**Comment by browningjp-datatonic** [comment]
Hi @clopezhrimac 

The data cleansing component is a placeholder for any pre-processing that you might want to do only to your training dataset to improve the performance of your model. For example, in your training dataset you might wish to remove rows that have a lot of null values. However, you should not remove these from your validation or test dataset, as this would make the model evaluation an unfair test.

The SQL query for this component can be found in `pipelines/pipelines/xgboost/training/queries/engineer_features.sql` - as you can see this is just a placeholder as it is a simple `SELECT *` query

**Comment by felix-datatonic** [comment]
@Linchin can you please close this issue?
