### ISSUE TITLE
No rule to make target 'compile-all-components'

### ISSUE THREAD

**Issue by arroyomejias** [GoogleCloudPlatform/vertex-pipelines-end-to-end-samples#66]
In the first step of the CICD pipeline `release.yaml`, the command `make compile-all-components` is executed, but there is no such rule within the makefile.  

`make: *** No rule to make target 'compile-all-components'.  Stop.`

**Comment by felix-datatonic** [comment]
Hi @arroyomejias, 

Thanks for this issue. Please check out the most recent [PR](https://github.com/GoogleCloudPlatform/vertex-pipelines-end-to-end-samples/pull/69) and [release](https://github.com/teamdatatonic/vertex-pipelines-end-to-end-samples/releases/tag/v2) which removes the need for `compile-all-components`.
